### ISSUE TITLE
Pre-release checklist

### ISSUE THREAD

**Issue by djkovrik** [djkovrik/YapTalker#12]
- [x] Complete TODOs
- [x] Fix all code analysis warnings
- [x] Russian translation
- [x] Launcher icon
- [x] Nav drawer image
- [x] Add EULA
- [x] Code refactoring and tests
- [x] Tablets layout
- [x] Setup CI
- [x] Gif support
- [x] Add crash reporting
- [x] ProGuard
